export type SequenceId = string;
export type SequenceFrameId = string;
export type SequenceReferenceId = string;
export type SequencePlanRevisionId = string;
export type SequenceAttemptId = string;
export type SequenceOutputId = string;

export const sequenceExecutionStatuses = [
  "draft",
  "awaiting-approval",
  "running",
  "partially-complete",
  "complete",
  "cancelled",
  "failed",
] as const;

export type SequenceExecutionStatus = (typeof sequenceExecutionStatuses)[number];

export type SequenceFrameStatus =
  | "pending"
  | "ready"
  | "running"
  | "succeeded"
  | "accepted"
  | "failed"
  | "cancelled";

export type SequenceReferenceRole =
  | "frame-specific"
  | "subject"
  | "character"
  | "product"
  | "brand"
  | "style"
  | "palette"
  | "typography"
  | "composition";

export type SequenceDependencyKind = "content" | "continuity" | "reference";

export type SequenceReferenceSource = Readonly<{
  kind: "upload" | "generated-output" | "imported-page";
  assetId: string;
  mimeType: string;
  byteSize: number;
  sourceSequenceId: SequenceId | null;
  sourceFrameId: SequenceFrameId | null;
  sourceOutputId: SequenceOutputId | null;
}>;

export type SequenceReference = Readonly<{
  id: SequenceReferenceId;
  order: number;
  label: string;
  role: SequenceReferenceRole;
  frameIds: readonly SequenceFrameId[];
  source: SequenceReferenceSource;
}>;

export type SequenceFrameDependency = Readonly<{
  frameId: SequenceFrameId;
  kind: SequenceDependencyKind;
}>;

export type SequenceFrame = Readonly<{
  id: SequenceFrameId;
  position: number;
  purpose: string;
  prompt: string;
  referenceIds: readonly SequenceReferenceId[];
  dependencies: readonly SequenceFrameDependency[];
  status: SequenceFrameStatus;
  attemptIds: readonly SequenceAttemptId[];
  acceptedOutputId: SequenceOutputId | null;
}>;

export type SequenceSharedRules = Readonly<{
  style: string | null;
  subject: string | null;
  character: string | null;
  product: string | null;
  palette: string | null;
  typography: string | null;
  composition: string | null;
}>;

export type SequencePlanRevision = Readonly<{
  id: SequencePlanRevisionId;
  revision: number;
  createdAt: string;
  plannerModelAlias: string;
  imageModelAlias: string;
  title: string;
  sequenceType: string;
  goal: string;
  countRationale: string;
  sharedRules: SequenceSharedRules;
  references: readonly SequenceReference[];
  frames: readonly SequenceFrame[];
  warnings: readonly string[];
  assumptions: readonly string[];
  approvedAt: string | null;
}>;

export type SequenceAttempt = Readonly<{
  id: SequenceAttemptId;
  frameId: SequenceFrameId;
  planRevisionId: SequencePlanRevisionId;
  attemptNumber: number;
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  startedAt: string | null;
  finishedAt: string | null;
  outputId: SequenceOutputId | null;
  replacesOutputId: SequenceOutputId | null;
  errorCode: string | null;
  retryable: boolean;
}>;

export type SequenceOutputLineage = Readonly<{
  id: SequenceOutputId;
  sequenceId: SequenceId;
  frameId: SequenceFrameId;
  planRevisionId: SequencePlanRevisionId;
  attemptId: SequenceAttemptId;
  generatedImageId: string;
  modelAlias: string;
  prompt: string;
  referenceIds: readonly SequenceReferenceId[];
  sourceOutputIds: readonly SequenceOutputId[];
  createdAt: string;
  acceptedAt: string | null;
  supersedesOutputId: SequenceOutputId | null;
}>;

export type SequenceExecutionState = Readonly<{
  status: SequenceExecutionStatus;
  activePlanRevisionId: SequencePlanRevisionId;
  nextFrameId: SequenceFrameId | null;
  imageCallsUsed: number;
  plannerCallsUsed: number;
  cancelRequestedAt: string | null;
  lastUpdatedAt: string;
}>;

/**
 * Durable aggregate metadata. Generated bytes remain in the existing generated-image
 * storage/history boundary; this record stores stable row IDs and immutable lineage.
 * Repositories must use `version` for optimistic concurrency on resume/retry writes.
 */
export type SequencePersistenceRecord = Readonly<{
  schemaVersion: 1;
  id: SequenceId;
  userId: string;
  version: number;
  createdAt: string;
  updatedAt: string;
  planRevisions: readonly SequencePlanRevision[];
  execution: SequenceExecutionState;
  attempts: readonly SequenceAttempt[];
  outputs: readonly SequenceOutputLineage[];
}>;

export type SaveSequenceResult =
  | { status: "saved"; record: SequencePersistenceRecord }
  | { status: "conflict"; currentVersion: number }
  | { status: "not-found" };

export interface SequenceRepository {
  load(sequenceId: SequenceId, userId: string): Promise<SequencePersistenceRecord | null>;
  save(record: SequencePersistenceRecord, expectedVersion: number): Promise<SaveSequenceResult>;
}

export type BeginSequenceAttemptFailure =
  | "record-not-running"
  | "cancellation-requested"
  | "plan-not-approved"
  | "frame-not-found"
  | "dependencies-incomplete"
  | "frame-already-complete"
  | "frame-not-retryable"
  | "frame-attempt-limit"
  | "image-call-limit"
  | "concurrency-limit";

export type BeginSequenceAttemptResult =
  | { ok: true; record: SequencePersistenceRecord; attempt: SequenceAttempt }
  | { ok: false; reason: BeginSequenceAttemptFailure };
